#!/bin/sh

LOCALE_RELATIVE_PATH="./locale"

for language in en
do
	test -f "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/sb.mo" && mv "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/sb.mo" "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/sb.mo.old"
	msgfmt "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/sb.po" --output-file="$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/sb.mo"
done
